<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputPath>$(MSBuildThisFileDirectory)..\Build\</OutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="abname" /> <!-- Change abname to the name of the assetbundle or remove if it is not a custom plant mod -->
  </ItemGroup>

  <!-- Import shared references -->
  <Import Project="$(MSBuildThisFileDirectory)..\ModReferences.props" />

</Project>
