<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <!-- Output DLLs into combinemod/Build -->
    <OutputPath>$(MSBuildThisFileDirectory)..\Build\</OutputPath>

    <!-- IL2CPP mods don't need dependency/runtime files -->
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <!-- Import shared references -->
  <Import Project="$(MSBuildThisFileDirectory)..\ModReferences.props" />
  
  <ItemGroup>
    <Reference Include="UltimateSniper" Private="false">
      <HintPath>UltimateSniperAndUltimateMegaGatlingPea.dll</HintPath>
    </Reference>
    
  </ItemGroup>

</Project>
