<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <!-- Output DLLs into combinemod/Build -->
    <OutputPath>$(MSBuildThisFileDirectory)..\Build\</OutputPath>

    <!-- IL2CPP mods don't need dependency/runtime files -->
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Project.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageReference Include="System.Collections.Immutable" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core" Private="false">
      <HintPath>..\lib\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader.Core" Private="false">
      <HintPath>..\lib\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.Common" Private="false">
      <HintPath>..\lib\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP" Private="false">
      <HintPath>..\lib\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
